Vagrant.configure("2") do |config|
  config.vm.define "pchambonS" do |pchambonS|
    pchambonS.vm.box = "generic/alpine317"
    pchambonS.vm.network "private_network", ip: "192.168.56.110"
    pchambonS.vm.synced_folder ".", "/sync"
    pchambonS.vm.provision "ControllerScript", type: "shell", path: "./scripts/Install.sh"
    pchambonS.vm.hostname = "pchambonS"
    pchambonS.vm.provider "virtualbox" do |vb|
      vb.name = "pchambonS"
      vb.memory = 1024
      vb.cpus = 1 
      end
  end
end
