apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-deployment
  labels:
    app: app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-3-index
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: app-3-index
        configMap:
          name: app-3-index-configmap

