Vagrant.configure("2") do |config|
  config.vm.define "xperrinS" do |xperrinS|
    xperrinS.vm.box = "generic/alpine317"
    xperrinS.vm.network "private_network", ip: "192.168.56.110"
    xperrinS.vm.synced_folder ".", "/sync"
    xperrinS.vm.provision "Provisioning script", type: "shell", path: "./scripts/provision.sh"
    xperrinS.vm.hostname = "xperrinS"
    xperrinS.vm.provider "virtualbox" do |vb|
      config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 8888, host: 8888
      vb.name = "xperrinS"
      vb.memory = 8192
      vb.cpus = 12
      end
  end
end
