Vagrant.configure("2") do |config|
  config.vm.define "pchambonS" do |pchambonS|
    pchambonS.vm.box = "generic/alpine317"
    pchambonS.vm.network "private_network", ip: "192.168.56.110"
    pchambonS.vm.synced_folder ".", "/sync"
    pchambonS.vm.provision "ControllerScript", type: "shell", path: "./scripts/Install.sh"
    pchambonS.vm.hostname = "pchambonS"
    pchambonS.vm.provider "virtualbox" do |vb|
      config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 8888, host: 8888
      vb.name = "pchambonS"
      vb.memory = 4096
      vb.cpus = 8
      end
  end
end
